### ISSUE TITLE
The backslash directory separator seems doesn't work well

### ISSUE THREAD

**Issue by adibenc** [AnandPilania/php-android-cli#5]
The backslash directory separator seems doesn't work well on linux. It created folder named as it is instead of make dir inside the project folder etc.
![image](https://user-images.githubusercontent.com/24596057/69059568-5ba9d000-0a48-11ea-8f8a-146da36642d4.png)

**Comment by homeraptor** [comment]
I created fork that fixes this issue.
I replaced path separators to unix separator('/') and end line separators to \n. That should work also in Windows, but I not checked.
Also added [INSTALL.md](https://github.com/homperator/php-android-cli/blob/master/INSTALL.md)
I not created pull request, because INSTALL.md should be reviewed and fixed.
phpandroid.phar should be rebuilded and installed folowing INSTALL.md.

**Comment by adibenc** [comment]
i also tried with DIRECTORY_SEPARATOR constant from php's. still work on my local repo.
